include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:

  errors:
    todo: warning
    avoid_print: ignore
    avoid_function_literals_in_foreach_calls: ignore
    invalid_annotation_target: ignore

  exclude:
    - "**/*.gr.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/__brick__/**"
    - "build/**"

linter:
  rules:
    - no-boolean-literal-compare
    - prefer_single_quotes
    - missing-test-assertion:
        include-assertions:
          - verify
          - verifyNoMoreInteractions
          - verifyZeroInteractions
          - verifyInOrder
          - verifyNever
    - prefer-commenting-analyzer-ignores
    - prefer-trailing-comma
    - prefer-correct-identifier-length:
        min-identifier-length: 3
    - member-ordering:
        order:
          - public-fields
          - private-fields
          - constructors
          - close-method
          - dispose-method
        widgets-order:
          - constructor
          - init-state-method
          - build-method
          - did-change-dependencies-method
          - did-update-widget-method
          - dispose-method
