name: hotels_booking
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  dio: ^5.7.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
